apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APPLICATION_NAME}
spec:
  schedule: "30 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ${APPLICATION_NAME}
              image: ${CONTAINER_IMAGE_TAGGED}
              env:
                - name: LOKI_URL
                  value: http://loki.monitoring:3100
                # - name: FINANCES_API_TOKEN
                #   valueFrom:
                #     secretKeyRef:
                #       name: oicd-token
                #       key: OIDC_M2M_ACCESS_TOKEN
              envFrom:
                - secretRef:
                    name: resona-scraper
