apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APPLICATION_NAME}
spec:
  schedule: "30 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ${APPLICATION_NAME}
              image: ${CONTAINER_IMAGE_TAGGED}
              env:
                - name: LOKI_URL
                  value: http://loki.monitoring:3100
              envFrom:
                - secretRef:
                    name: resona-scraper
